### ISSUE TITLE
The teleop configuration does not affect the robot

### ISSUE THREAD

**Issue by CyrillePierre** [FiraHackathon/hackathon2025_ws#6]
If we try to change the maximal speed of the robot in the slow or turbo mode in `teleop.yaml`, the robot stay at the same maximal speed of 2 m/s.

**Comment by vincentrou** [comment]
max speed has been change from 2 m/s to 4 m/s.
https://github.com/Romea/adap2e/commit/7f326dd48f4e9d868766ece96ba83099b7f581bb
